# Generated by Django 5.2 on 2025-06-15 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline_code', models.CharField(db_index=True, max_length=10, verbose_name='Airline code')),
                ('flight_number', models.CharField(db_index=True, max_length=10, verbose_name='Flight number')),
                ('departure_date', models.DateField(db_index=True, verbose_name='Departure date')),
                ('extra_data', models.JSONField(blank=True, default=dict, null=True, verbose_name='Extra data')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated at')),
            ],
        ),
    ]
